Cute=[
'aww',
'cats',
'animalsbeingjerks',
'animalsbeingbros',
'Awwducational',
'dogs',
'corgi',
'thisismylifenow',
'blep',
'eyebleach',
'tippytaps',
'awww',
'babycorgis',
'rarepuppers'
]
Unexpected=["Unexpected"]
People_positive=[
"HumansBeingBros",
"MadeMeSmile",
"ContagiousLaughter",
"nonononoyes"
]
People_negative=[
"Whatcouldgowrong",
"WatchPeopleDieInside",
"Instant_regret"
"IdiotsInCars"
]
Misc=[
"WoahDude",
"Interestingasfuck",
"Damnthatsinteresting"

]
Funny=["funny","ContagiousLaughter"]
Subreddits=[Cute,Unexpected,People_negative,People_positive,Misc,Funny]
